import { Injectable } from '@nestjs/common';

@Injectable()
export class GeneratedFileDetectorService {
  isGenerated(relativePath: string, content: string): boolean {
    const loweredPath = relativePath.toLowerCase();
    if (
      loweredPath.includes('.generated.') ||
      loweredPath.endsWith('.min.js') ||
      loweredPath.endsWith('.min.ts')
    ) {
      return true;
    }

    const header = content.slice(0, 400).toLowerCase();
    return (
      header.includes('auto-generated') ||
      header.includes('autogenerated') ||
      header.includes('generated by')
    );
  }
}
