export const ONBOARDING_GUIDE_STORAGE = Symbol('ONBOARDING_GUIDE_STORAGE');
export const INDEXED_TOPOLOGY_DATA_SOURCE = Symbol(
  'INDEXED_TOPOLOGY_DATA_SOURCE',
);
export const GUIDE_GENERATORS = Symbol('GUIDE_GENERATORS');
export const GUIDE_TEMPLATE_CONTRACTS_PROVIDER = Symbol(
  'GUIDE_TEMPLATE_CONTRACTS_PROVIDER',
);
